name: wat pages build archive

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build pages
      run: |
        python3 build-index.py fs-path-pages/ > fs-path-pages/index.json
    - name: Bundle archive
      run: |
        cd fs-path-pages; zip fs-path-pages.zip ./*.md ./*.json
    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        name: fs-path-pages
        path: fs-path-pages/fs-path-pages.zip